name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux CI

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec

  openbsd:
    runs-on: macos-12
    name: OpenBSD CI

    steps:
    - uses: actions/checkout@v4
    - name: Run OpenBSD
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add crystal
        run: |
          shards install
          crystal spec

  freebsd:
    runs-on: macos-12
    name: FreeBSD CI

    steps:
    - uses: actions/checkout@v4
    - name: Run FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y crystal shards
        run: |
          shards install
          crystal spec
